version: 1.0.{build}
    platform:
      - x64

    install:
      - cmd: echo "Downloading conan..."
      - ps: wget http://downloads.conan.io/latest_windows -OutFile conan_installer.exe
      - cmd: conan_installer.exe /VERYSILENT
      - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
      - cmd: conan --version

    build_script:
      - cmd: conan test -s compiler="Visual Studio" -s compiler.version=14 -s arch=x86_64 -s build_type=Debug -s compiler.runtime=MDd -o wxWidgets_custom:shared=True
      - cmd: conan test -s compiler="Visual Studio" -s compiler.version=14 -s arch=x86_64 -s build_type=Release -s compiler.runtime=MD -o wxWidgets_custom:shared=True
      - cmd: conan test -s compiler="Visual Studio" -s compiler.version=14 -s arch=x86_64 -s build_type=Release -s compiler.runtime=MD -o wxWidgets_custom:shared=False
      - cmd: conan test -s compiler="Visual Studio" -s compiler.version=14 -s arch=x86_64 -s build_type=Release -s compiler.runtime=MT -o wxWidgets_custom:shared=False
